/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication5;

import java.util.Random;
import static javaapplication5.JavaApplication5.degistir;
import static javaapplication5.JavaApplication5.diziYerlestir;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author sariz
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initiCennetze the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manuel = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        paz1 = new javax.swing.JTextField();
        paz2 = new javax.swing.JTextField();
        paz3 = new javax.swing.JTextField();
        paz4 = new javax.swing.JTextField();
        paz5 = new javax.swing.JTextField();
        gonderButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sal1 = new javax.swing.JTextField();
        car1 = new javax.swing.JTextField();
        per1 = new javax.swing.JTextField();
        cum1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sal2 = new javax.swing.JTextField();
        sal3 = new javax.swing.JTextField();
        sal4 = new javax.swing.JTextField();
        sal5 = new javax.swing.JTextField();
        car2 = new javax.swing.JTextField();
        car3 = new javax.swing.JTextField();
        car4 = new javax.swing.JTextField();
        car5 = new javax.swing.JTextField();
        per2 = new javax.swing.JTextField();
        per3 = new javax.swing.JTextField();
        per4 = new javax.swing.JTextField();
        per5 = new javax.swing.JTextField();
        cum2 = new javax.swing.JTextField();
        cum3 = new javax.swing.JTextField();
        cum4 = new javax.swing.JTextField();
        cum5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        hesaplaButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        manuel.setLocationByPlatform(true);
        manuel.setMinimumSize(new java.awt.Dimension(500, 400));
        manuel.setPreferredSize(new java.awt.Dimension(500, 347));

        jLabel1.setText("Cennet");

        jLabel2.setText("Büşra");

        jLabel3.setText("Emine");

        jLabel4.setText("Esra");

        jLabel5.setText("Gülçin");

        paz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paz3ActionPerformed(evt);
            }
        });

        paz5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paz5ActionPerformed(evt);
            }
        });

        gonderButton.setText("Gönder");
        gonderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gonderButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("1");

        jLabel7.setText("2");

        jLabel8.setText("3");

        jLabel9.setText("4");

        jLabel10.setText("5");

        car2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car2ActionPerformed(evt);
            }
        });

        cum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cum5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gonderButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paz1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(paz2)
                            .addComponent(paz3)
                            .addComponent(paz4)
                            .addComponent(paz5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sal4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                        .addComponent(sal3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sal2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sal5))
                                    .addComponent(sal1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(car3)
                                    .addComponent(car2)
                                    .addComponent(car4)
                                    .addComponent(car5)
                                    .addComponent(car1))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(per2)
                                        .addComponent(per3)
                                        .addComponent(per4)
                                        .addComponent(per5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(per1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cum2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cum3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cum4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cum5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cum1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(386, 386, 386))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(paz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(per1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(paz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(per2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paz3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(per3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(paz4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(per4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(paz5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(per5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(gonderButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout manuelLayout = new javax.swing.GroupLayout(manuel.getContentPane());
        manuel.getContentPane().setLayout(manuelLayout);
        manuelLayout.setHorizontalGroup(
            manuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        manuelLayout.setVerticalGroup(
            manuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        hesaplaButton.setText("Hesapla");
        hesaplaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Manuel Değer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hesaplaButton)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hesaplaButton)
                    .addComponent(jButton1))
                .addGap(270, 270, 270))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hesaplaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaButtonActionPerformed
        String[] hocalar = {"Cennet","Büşra","Emine","Esra","Gülçin"};
        String[] list = {"Cennet","Büşra","Emine","Esra","Gülçin"};
        int[] sht = new int[5];
        int[][] hocaDers1 = new int[5][5];
        hocaDers1 = diziYerlestir(hocaDers1);
        list = JavaApplication5.listeDegistir(list);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,0);
        }
        hocaDers1 = diziYerlestir(hocaDers1);
        list = JavaApplication5.listeDegistir(list);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,1);
        }
        hocaDers1 = diziYerlestir(hocaDers1);
        list = JavaApplication5.listeDegistir(list);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,2);
        }
        hocaDers1 = diziYerlestir(hocaDers1);
        list = JavaApplication5.listeDegistir(list);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,3);
        }
        hocaDers1 = diziYerlestir(hocaDers1);
        list = JavaApplication5.listeDegistir(list);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,4);
        }
    }//GEN-LAST:event_hesaplaButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.manuel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void paz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paz3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paz3ActionPerformed

    private void paz5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paz5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paz5ActionPerformed

    private void car2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car2ActionPerformed

    private void cum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cum5ActionPerformed

        int count=0;
    private void gonderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gonderButtonActionPerformed
        String[] hocalar = {"Cennet","Büşra","Emine","Esra","Gülçin"};
        String[] list = {"Cennet","Büşra","Emine","Esra","Gülçin"};
        int[] sht = new int[5];
        int[][] hocaDers1 = new int[5][5];
        hocaDers1[0][0]=Integer.parseInt(paz1.getText());
        hocaDers1[0][1]=Integer.parseInt(paz2.getText());
        hocaDers1[0][2]=Integer.parseInt(paz3.getText());
        hocaDers1[0][3]=Integer.parseInt(paz4.getText());
        hocaDers1[0][4]=Integer.parseInt(paz5.getText());
        hocaDers1[1][0]=Integer.parseInt(sal1.getText());
        hocaDers1[1][1]=Integer.parseInt(sal2.getText());
        hocaDers1[1][2]=Integer.parseInt(sal3.getText());
        hocaDers1[1][3]=Integer.parseInt(sal4.getText());
        hocaDers1[1][4]=Integer.parseInt(sal5.getText());
        hocaDers1[2][0]=Integer.parseInt(car1.getText());
        hocaDers1[2][1]=Integer.parseInt(car2.getText());
        hocaDers1[2][2]=Integer.parseInt(car3.getText());
        hocaDers1[2][3]=Integer.parseInt(car4.getText());
        hocaDers1[2][4]=Integer.parseInt(car5.getText());
        hocaDers1[3][0]=Integer.parseInt(per1.getText());
        hocaDers1[3][1]=Integer.parseInt(per2.getText());
        hocaDers1[3][2]=Integer.parseInt(per3.getText());
        hocaDers1[3][3]=Integer.parseInt(per4.getText());
        hocaDers1[3][4]=Integer.parseInt(per5.getText());
        hocaDers1[4][0]=Integer.parseInt(cum1.getText());
        hocaDers1[4][1]=Integer.parseInt(cum2.getText());
        hocaDers1[4][2]=Integer.parseInt(cum3.getText());
        hocaDers1[4][3]=Integer.parseInt(cum4.getText());
        hocaDers1[4][4]=Integer.parseInt(cum5.getText());
        if(count==0){
        hocaDers1 = diziYerlestir(hocaDers1);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,0);
        }}
        else if(count==1){
        hocaDers1 = diziYerlestir(hocaDers1);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,1);
        }}
        else if(count==2){
        hocaDers1 = diziYerlestir(hocaDers1);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,2);
        }}
        else if(count==3){
        hocaDers1 = diziYerlestir(hocaDers1);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,3);
        }}
        else{
        hocaDers1 = diziYerlestir(hocaDers1);
        degistir(list, hocaDers1, sht, hocalar);
        for(int i=0;i<list.length;i++){
            this.jTable1.setValueAt(hocalar[i], i,4);
        }}
        count+=1;
    }//GEN-LAST:event_gonderButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        int i,j;
        int[] sht = new int[5];
        Random rnd = new Random();
        String[] hocalar = {"Cennet","Büşra","Emine","Esra","Gülçin"};
        String[] list = {"Cennet","Büşra","Emine","Esra","Gülçin"};
        int[][] hocaDers1 = new int[5][5];
        hocaDers1 = diziYerlestir(hocaDers1);
        for(i=0;i<hocaDers1.length;i++){
            System.out.print(hocalar[i]+" \t");
            for(j=0;j<hocaDers1.length;j++){
                System.out.print(hocaDers1[i][j]+" ");
            }
            System.out.println("\n");
        }
        System.out.println(degistir(list, hocaDers1, sht, hocalar)+"");
        System.out.print(hocalar[0]+" "+hocalar[1]+" "+hocalar[2]+" "+hocalar[3]+" "+hocalar[4]+"\n");
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField car1;
    private javax.swing.JTextField car2;
    private javax.swing.JTextField car3;
    private javax.swing.JTextField car4;
    private javax.swing.JTextField car5;
    private javax.swing.JTextField cum1;
    private javax.swing.JTextField cum2;
    private javax.swing.JTextField cum3;
    private javax.swing.JTextField cum4;
    private javax.swing.JTextField cum5;
    private javax.swing.JButton gonderButton;
    private javax.swing.JButton hesaplaButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFrame manuel;
    private javax.swing.JTextField paz1;
    private javax.swing.JTextField paz2;
    private javax.swing.JTextField paz3;
    private javax.swing.JTextField paz4;
    private javax.swing.JTextField paz5;
    private javax.swing.JTextField per1;
    private javax.swing.JTextField per2;
    private javax.swing.JTextField per3;
    private javax.swing.JTextField per4;
    private javax.swing.JTextField per5;
    private javax.swing.JTextField sal1;
    private javax.swing.JTextField sal2;
    private javax.swing.JTextField sal3;
    private javax.swing.JTextField sal4;
    private javax.swing.JTextField sal5;
    // End of variables declaration//GEN-END:variables
}
